/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.coursework2.view;

import edu.ijse.coursework2.dto.UserDto;
import edu.ijse.coursework2.util.Roles;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class DashboardView extends javax.swing.JFrame {
    
    private final UserDto currentUser;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardView.class.getName());

    /**
     * Creates new form DashboardView
     * @param user
     */
    public DashboardView(UserDto user) {
        this.currentUser = user;
        
        initComponents();
        
        loadUserProfile();
        applyAccessControl();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnCustomerManagement = new javax.swing.JButton();
        btnOverdueRentals = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnEquipmentManagement = new javax.swing.JButton();
        btnReturnSettlement = new javax.swing.JButton();
        btnRentalManagement = new javax.swing.JButton();
        btnReservationManagement = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMaster = new javax.swing.JMenu();
        jMenuItemBranch = new javax.swing.JMenuItem();
        jMenuItemUsers = new javax.swing.JMenuItem();
        jMenuItemSettings = new javax.swing.JMenuItem();
        jMenuOperations = new javax.swing.JMenu();
        jMenuItemCustomerM = new javax.swing.JMenuItem();
        jMenuItemEquipmentM = new javax.swing.JMenuItem();
        jMenuItemReservationM = new javax.swing.JMenuItem();
        jMenuItemRentalM = new javax.swing.JMenuItem();
        jMenuItemReturnSettlement = new javax.swing.JMenuItem();
        jMenuItemOverdueRental = new javax.swing.JMenuItem();
        jMenuReports = new javax.swing.JMenu();
        jMenuAccount = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabel1ComponentAdded(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnCustomerManagement.setText("Customer management");
        btnCustomerManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerManagementActionPerformed(evt);
            }
        });

        btnOverdueRentals.setText("Overdue rentals");
        btnOverdueRentals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverdueRentalsActionPerformed(evt);
            }
        });

        btnReports.setText("Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnEquipmentManagement.setText("Equipment management");
        btnEquipmentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipmentManagementActionPerformed(evt);
            }
        });

        btnReturnSettlement.setText("Return/Settlement");
        btnReturnSettlement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnSettlementActionPerformed(evt);
            }
        });

        btnRentalManagement.setText("Rental management");
        btnRentalManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentalManagementActionPerformed(evt);
            }
        });

        btnReservationManagement.setText("Reservation management");
        btnReservationManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservationManagementActionPerformed(evt);
            }
        });

        jMenuMaster.setText("Master");

        jMenuItemBranch.setText("Branch");
        jMenuItemBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBranchActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemBranch);

        jMenuItemUsers.setText("Users");
        jMenuItemUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsersActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemUsers);

        jMenuItemSettings.setText("Settings");
        jMenuItemSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSettingsActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemSettings);

        jMenuBar1.add(jMenuMaster);

        jMenuOperations.setText("Operations");

        jMenuItemCustomerM.setText("Customer management");
        jMenuOperations.add(jMenuItemCustomerM);

        jMenuItemEquipmentM.setText("Equipment management");
        jMenuOperations.add(jMenuItemEquipmentM);

        jMenuItemReservationM.setText("Reservation management");
        jMenuOperations.add(jMenuItemReservationM);

        jMenuItemRentalM.setText("Rental management");
        jMenuOperations.add(jMenuItemRentalM);

        jMenuItemReturnSettlement.setText("Return/Settlement");
        jMenuOperations.add(jMenuItemReturnSettlement);

        jMenuItemOverdueRental.setText(" Overdue rental");
        jMenuOperations.add(jMenuItemOverdueRental);

        jMenuBar1.add(jMenuOperations);

        jMenuReports.setText("Reports");
        jMenuBar1.add(jMenuReports);

        jMenuAccount.setText("Account");

        jMenuItemLogout.setText("Log out");
        jMenuAccount.add(jMenuItemLogout);

        jMenuBar1.add(jMenuAccount);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(btnRentalManagement)
                            .addGap(18, 18, 18)
                            .addComponent(btnReturnSettlement)
                            .addGap(18, 18, 18)
                            .addComponent(btnOverdueRentals)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReports))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(btnCustomerManagement)
                            .addGap(18, 18, 18)
                            .addComponent(btnEquipmentManagement)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnReservationManagement)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCustomerManagement)
                    .addComponent(btnEquipmentManagement)
                    .addComponent(btnReservationManagement))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturnSettlement)
                    .addComponent(btnOverdueRentals)
                    .addComponent(btnReports)
                    .addComponent(btnRentalManagement))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        logOut();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnEquipmentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipmentManagementActionPerformed
        equipmentView();
    }//GEN-LAST:event_btnEquipmentManagementActionPerformed

    private void btnReturnSettlementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnSettlementActionPerformed
        returnSettlementView();
    }//GEN-LAST:event_btnReturnSettlementActionPerformed

    private void btnCustomerManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerManagementActionPerformed
        customerView();
    }//GEN-LAST:event_btnCustomerManagementActionPerformed

    private void btnReservationManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationManagementActionPerformed
        reservationView();
    }//GEN-LAST:event_btnReservationManagementActionPerformed

    private void btnRentalManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentalManagementActionPerformed
        rentalView();
    }//GEN-LAST:event_btnRentalManagementActionPerformed

    private void btnOverdueRentalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverdueRentalsActionPerformed
        overdueView();
    }//GEN-LAST:event_btnOverdueRentalsActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        reportsView();
    }//GEN-LAST:event_btnReportsActionPerformed

    private void jMenuItemBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemBranchActionPerformed

    private void jMenuItemUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemUsersActionPerformed

    private void jMenuItemSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSettingsActionPerformed

    private void jLabel1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel1ComponentAdded
        
    }//GEN-LAST:event_jLabel1ComponentAdded

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerManagement;
    private javax.swing.JButton btnEquipmentManagement;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOverdueRentals;
    private javax.swing.JButton btnRentalManagement;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnReservationManagement;
    private javax.swing.JButton btnReturnSettlement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAccount;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemBranch;
    private javax.swing.JMenuItem jMenuItemCustomerM;
    private javax.swing.JMenuItem jMenuItemEquipmentM;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemOverdueRental;
    private javax.swing.JMenuItem jMenuItemRentalM;
    private javax.swing.JMenuItem jMenuItemReservationM;
    private javax.swing.JMenuItem jMenuItemReturnSettlement;
    private javax.swing.JMenuItem jMenuItemSettings;
    private javax.swing.JMenuItem jMenuItemUsers;
    private javax.swing.JMenu jMenuMaster;
    private javax.swing.JMenu jMenuOperations;
    private javax.swing.JMenu jMenuReports;
    // End of variables declaration//GEN-END:variables

    private void applyAccessControl() {
        if (currentUser == null) return; // Fail safe
        String role = currentUser.getRole();

        if (Roles.ADMIN.equals(role)) {
            setAdminAccess(true); // Enable everything
        } else if (Roles.BRANCH_MANAGER.equals(role)) {
            setBranchManagerAccess(true); // Limit to branch ops only
        } else if (Roles.STAFF.equals(role)) {
            setStaffAccess(true); // Enable only staff-related ops
        }
    }

    private void setAdminAccess(boolean enabled) {
        btnCustomerManagement.setEnabled(enabled);
        btnEquipmentManagement.setEnabled(enabled);
        btnReservationManagement.setEnabled(enabled);
        btnRentalManagement.setEnabled(enabled);
        btnReturnSettlement.setEnabled(enabled);
        btnOverdueRentals.setEnabled(enabled);
        btnReports.setEnabled(enabled);

        jMenuItemBranch.setEnabled(enabled);
        jMenuItemUsers.setEnabled(enabled);
        jMenuItemSettings.setEnabled(enabled);
    }

    private void setBranchManagerAccess(boolean enabled) {
        btnCustomerManagement.setEnabled(enabled);
        btnEquipmentManagement.setEnabled(enabled);
        btnReservationManagement.setEnabled(enabled);
        btnRentalManagement.setEnabled(enabled);
        btnReturnSettlement.setEnabled(enabled);
        btnOverdueRentals.setEnabled(enabled);
        btnReports.setEnabled(enabled);

        jMenuItemBranch.setEnabled(false); // Hide for branch managers
        jMenuItemUsers.setEnabled(false); // Hide for branch managers
        jMenuItemSettings.setEnabled(false); // Hide for branch managers
    }

    private void setStaffAccess(boolean enabled) {
        btnCustomerManagement.setEnabled(enabled);
        btnEquipmentManagement.setEnabled(enabled);
        btnReservationManagement.setEnabled(enabled);
        btnRentalManagement.setEnabled(enabled);
        btnReturnSettlement.setEnabled(enabled);
        btnOverdueRentals.setEnabled(enabled);
        btnReports.setEnabled(false); // Staff shouldn't have access to reports

        jMenuItemBranch.setEnabled(false); // Hide for staff
        jMenuItemUsers.setEnabled(false); // Hide for staff
        jMenuItemSettings.setEnabled(false); // Hide for staff
    }


    
    
    private void logOut() {
        int opt = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Confirm Logout", JOptionPane.YES_NO_OPTION);
        if (opt == JOptionPane.YES_OPTION) {
        new LoginView().setVisible(true);  // Open Login screen again
        dispose();  // Close the current DashboardView
    }
    }

    private void customerView() {
        new CustomerView(currentUser).setVisible(true);
    }

    private void equipmentView() {
        new EquipmentView(currentUser).setVisible(true);
    }

    private void reservationView() {
        new ReservationView(currentUser).setVisible(true); 
    }

    private void rentalView() {
        new RentalView(currentUser).setVisible(true);
    }

    private void returnSettlementView() {
        new ReturnSettlementView(currentUser).setVisible(true);
    }

    private void overdueView() {
        new OverdueView(currentUser).setVisible(true);
    }

    private void reportsView() {
        new ReportsView(currentUser).setVisible(true);
    }

    private void loadUserProfile() {
        // 1. Safety Check: Always check for null in production code
        if (currentUser == null) {
            jLabel1.setText("Welcome, Guest");
            return;
        }

        // 2. Data Extraction: Get the data you need (Name, Role, etc.)
        // Assuming your UserDto has getUsername() or getName(). 
        // Adjust .getName() to whatever your DTO actually has.
        String userName = currentUser.getFullName(); 
        String userRole = currentUser.getRole();

        // 3. UI Update: Set the text clearly
        // HTML in Swing JLabels allows for multi-line or styled text easily
        jLabel1.setText("<html>Welcome, <b>" + userName + "</b> (" + userRole + ")</html>");
        
    }
}
