/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.coursework2.view;

import edu.ijse.coursework2.controller.EquipmentController;
import edu.ijse.coursework2.dto.EquipmentDto;
import edu.ijse.coursework2.dto.UserDto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class EquipmentView extends javax.swing.JFrame {
    
    private  UserDto currentUser;
    private final EquipmentController equipmentController = new EquipmentController();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EquipmentView.class.getName());

    /**
     * Creates new form EquipmentView
     * @param user
     */
    public EquipmentView(UserDto user) {
        this.currentUser = user;
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSecurityDeposite = new javax.swing.JTextField();
        txtBranchID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEquipmentID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtCategoryID = new javax.swing.JTextField();
        txtPurchaseYear = new javax.swing.JTextField();
        txtBasePrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtActiveNot = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Branch ID");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Equipment Management");

        jLabel2.setText("Equipment ID");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Category ID");

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Purchase Year");

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Base price per day");

        jLabel6.setText("Security deposite");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Status");

        jLabel9.setText("Active/Not");

        jLabel10.setText("Brand");

        jLabel11.setText("Model");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEquipmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCategoryID, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(419, 419, 419))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBranchID, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSecurityDeposite, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPurchaseYear, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(7, 7, 7))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtActiveNot, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEquipmentID)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPurchaseYear)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoryID)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBasePrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSecurityDeposite)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBranchID))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtActiveNot))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBrand))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saveEquipment();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        updateEquipment();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        deleteEquipment();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        
        if (row != -1) {
            // Fill the text fields with data from the selected row
            txtEquipmentID.setText(jTable1.getValueAt(row, 0).toString());
            txtCategoryID.setText(jTable1.getValueAt(row, 1).toString());
            txtBranchID.setText(jTable1.getValueAt(row, 2).toString());
            txtBrand.setText(jTable1.getValueAt(row, 3).toString());
            txtModel.setText(jTable1.getValueAt(row, 4).toString());
            txtPurchaseYear.setText(jTable1.getValueAt(row, 5).toString());
            txtBasePrice.setText(jTable1.getValueAt(row, 6).toString());
            txtSecurityDeposite.setText(jTable1.getValueAt(row, 7).toString());
            txtStatus.setText(jTable1.getValueAt(row, 8).toString());
            
            // Special handling: Convert "Active" string back to "1" so Update works
            String activeStatus = jTable1.getValueAt(row, 9).toString();
            if (activeStatus.equalsIgnoreCase("Active")) {
                txtActiveNot.setText("1");
            } else {
                txtActiveNot.setText("0");
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtActiveNot;
    private javax.swing.JTextField txtBasePrice;
    private javax.swing.JTextField txtBranchID;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCategoryID;
    private javax.swing.JTextField txtEquipmentID;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPurchaseYear;
    private javax.swing.JTextField txtSecurityDeposite;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

    private void saveEquipment() {
        String equipmentId = txtEquipmentID.getText().trim();
        String categoryId = txtCategoryID.getText().trim();
        String branchId = txtBranchID.getText().trim();
        String brand = txtBrand.getText().trim();
        String model = txtModel.getText().trim();
        String purchaseYear = txtPurchaseYear.getText().trim();
        String basePrice = txtBasePrice.getText().trim();
        String securityDeposit = txtSecurityDeposite.getText().trim();
        String status = txtStatus.getText().trim();
        String active = txtActiveNot.getText().trim();

        // Check for empty fields and show a message
        if (equipmentId.isEmpty() || categoryId.isEmpty() || branchId.isEmpty() || brand.isEmpty() || 
            model.isEmpty() || purchaseYear.isEmpty() || basePrice.isEmpty() || securityDeposit.isEmpty() || 
            status.isEmpty() || active.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        // Convert text fields into appropriate data types
        int purchaseYearInt = Integer.parseInt(purchaseYear);
        double basePricePerDay = Double.parseDouble(basePrice);
        double securityDepositDouble = Double.parseDouble(securityDeposit);
        boolean isActive = active.equalsIgnoreCase("1");

        // Create a DTO object to pass to the controller
        EquipmentDto dto = new EquipmentDto(
                equipmentId, 
                categoryId, 
                branchId, 
                brand, 
                model, 
                purchaseYearInt, 
                basePricePerDay, 
                securityDepositDouble, 
                status, 
                isActive
        );

        try {
            // Call the controller's save method
            String response = equipmentController.saveEquipment(dto);
            JOptionPane.showMessageDialog(this, response);
            loadTable(); // Reload the table after save
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving equipment.");
            e.printStackTrace();
        }
    }

    private void updateEquipment() {
        String equipmentId = txtEquipmentID.getText().trim();
        String categoryId = txtCategoryID.getText().trim();
        String branchId = txtBranchID.getText().trim();
        String brand = txtBrand.getText().trim();
        String model = txtModel.getText().trim();
        String purchaseYear = txtPurchaseYear.getText().trim();
        String basePrice = txtBasePrice.getText().trim();
        String securityDeposit = txtSecurityDeposite.getText().trim();
        String status = txtStatus.getText().trim();
        String active = txtActiveNot.getText().trim();

        // Check for empty fields
        if (equipmentId.isEmpty() || categoryId.isEmpty() || branchId.isEmpty() || brand.isEmpty() || 
            model.isEmpty() || purchaseYear.isEmpty() || basePrice.isEmpty() || securityDeposit.isEmpty() || 
            status.isEmpty() || active.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        // Convert text fields into appropriate data types
        int purchaseYearInt = Integer.parseInt(purchaseYear);
        double basePricePerDay = Double.parseDouble(basePrice);
        double securityDepositDouble = Double.parseDouble(securityDeposit);
        boolean isActive = active.equalsIgnoreCase("1");

        // Create a DTO object to pass to the controller
        EquipmentDto dto = new EquipmentDto(
                equipmentId, 
                categoryId, 
                branchId, 
                brand, 
                model, 
                purchaseYearInt, 
                basePricePerDay, 
                securityDepositDouble, 
                status, 
                isActive
        );

        try {
            // Call the controller's update method
            String response = equipmentController.updateEquipment(dto);
            JOptionPane.showMessageDialog(this, response);
            loadTable(); // Reload the table after update
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating equipment.");
            e.printStackTrace();
        }
    }

    private void deleteEquipment() {
        String equipmentId = txtEquipmentID.getText().trim();

        // Check if the equipment ID is not empty
        if (equipmentId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please provide the Equipment ID to delete.");
            return;
        }

        try {
            // Call the controller's delete method
            String response = equipmentController.deleteEquipment(equipmentId);
            JOptionPane.showMessageDialog(this, response);
            loadTable(); // Reload the table after delete
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error deleting equipment.");
            e.printStackTrace();
        }
    }

    private void loadTable() {
        String[] columns = {"Equipment ID", "Category ID", "Branch ID", "Brand", "Model", "Purchase Year", 
                            "Base Price", "Security Deposit", "Status", "Active"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0);
        jTable1.setModel(dtm);

        try {
            // Call the controller to get all equipment records
            ArrayList<EquipmentDto> equipmentList = equipmentController.getAllEquipment();
            for (EquipmentDto equipment : equipmentList) {
                // Add each equipment record as a row in the table
                dtm.addRow(new Object[] {
                    equipment.getEquipmentId(),
                    equipment.getCategoryId(),
                    equipment.getBranchId(),
                    equipment.getBrand(),
                    equipment.getModel(),
                    equipment.getPurchaseYear(),
                    equipment.getBasePricePerDay(),
                    equipment.getSecurityDeposit(),
                    equipment.getStatus(),
                    equipment.isIsActive() ? "Active" : "Inactive"
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading equipment data.");
            e.printStackTrace();
        }
    }
}
