/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.coursework2.view;

import edu.ijse.coursework2.controller.CustomerController;
import edu.ijse.coursework2.controller.EquipmentController;
import edu.ijse.coursework2.controller.RentalController;
import edu.ijse.coursework2.dto.CustomerDto;
import edu.ijse.coursework2.dto.EquipmentDto;
import edu.ijse.coursework2.dto.RentalDto;
import edu.ijse.coursework2.dto.UserDto;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class RentalView extends javax.swing.JFrame {
    
    private  UserDto currentUser;
    
    //Controllers
    private final CustomerController customerController = new CustomerController();
    private final EquipmentController equipmentController = new EquipmentController();
    private final RentalController rentalController = new RentalController();
    
    // STATE VARIABLES (To store data temporarily before saving)
    private CustomerDto selectedCustomer;
    private EquipmentDto selectedEquipment;
    private double calculatedFinalTotal = 0.0;
    
    // FORMATTERS
    private final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentalView.class.getName());

    /**
     * Creates new form RentalView
     * @param user
     */
    public RentalView(UserDto user) {
        this.currentUser = user;
        initComponents();
        loadRentalsTable();
        generateRentalId();
    }
    
    private void generateRentalId() {
        // Simple ID generation for coursework: R + Current Time (last 5 digits)
        long time = System.currentTimeMillis();
        // You can use a label to show this if you want, or just keep it internal
        // For now, we will generate it when saving.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCustomerId = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        btnSearchCustomer = new javax.swing.JButton();
        lblCustomerName = new javax.swing.JLabel();
        lblMembership = new javax.swing.JLabel();
        lblEquipmentDetails = new javax.swing.JLabel();
        lblDailyPrice = new javax.swing.JLabel();
        lblCustomerId1 = new javax.swing.JLabel();
        txtEquipmentId = new javax.swing.JTextField();
        btnSearchEquipment = new javax.swing.JButton();
        lblAvailability = new javax.swing.JLabel();
        lblCustomerId2 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        lblCustomerId3 = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        lblTotalDays = new javax.swing.JLabel();
        lblBaseTotal = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lblDeposite = new javax.swing.JLabel();
        lblFinalTotal = new javax.swing.JLabel();
        btnPlaceRental = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rental Transaction ");

        lblCustomerId.setText("Customer ID");

        txtCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerIdActionPerformed(evt);
            }
        });

        btnSearchCustomer.setText("Search");
        btnSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustomerActionPerformed(evt);
            }
        });

        lblCustomerId1.setText("Equipment ID");

        txtEquipmentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEquipmentIdActionPerformed(evt);
            }
        });

        btnSearchEquipment.setText("Search");
        btnSearchEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEquipmentActionPerformed(evt);
            }
        });

        lblCustomerId2.setText("Start Date");

        txtStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartDateActionPerformed(evt);
            }
        });

        lblCustomerId3.setText("End Date");

        txtEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndDateActionPerformed(evt);
            }
        });

        btnCalculate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCalculate.setText("Check Availability & Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblTotalDays.setText("Total Days");

        lblBaseTotal.setText("Base Rental");

        lblDiscount.setText("Discount");

        lblDeposite.setText("Security Deposite");

        lblFinalTotal.setText("FINAL PAYABLE");

        btnPlaceRental.setText("Place Rental");
        btnPlaceRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceRentalActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCustomerId2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCustomerId3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchCustomer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMembership, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCustomerId1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEquipmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchEquipment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEquipmentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDailyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCalculate, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalDays, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBaseTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDeposite, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFinalTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPlaceRental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchCustomer)
                        .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCustomerId1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEquipmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchEquipment)
                        .addComponent(lblEquipmentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDailyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerId2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerId3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalDays, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBaseTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDeposite, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnPlaceRental, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFinalTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerIdActionPerformed

    private void txtEquipmentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEquipmentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEquipmentIdActionPerformed

    private void txtStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateActionPerformed

    private void txtEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndDateActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        calculate();
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed
        String id = txtCustomerId.getText().trim();
        try {
            selectedCustomer = customerController.searchCustomer(id);
            if (selectedCustomer != null) {
                lblCustomerName.setText("Name: " + selectedCustomer.getFullName());
                lblMembership.setText("Membership: " + selectedCustomer.getMembershipLevelCode());
            } else {
                JOptionPane.showMessageDialog(this, "Customer not found!");
                selectedCustomer = null;
                lblCustomerName.setText("Name: -");
                lblMembership.setText("Membership: -");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error searching customer");
        }
    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    private void btnSearchEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEquipmentActionPerformed
        String id = txtEquipmentId.getText().trim();
        try {
            selectedEquipment = equipmentController.searchEquipment(id); // Ensure searchEquipment exists in EquipmentController!
            if (selectedEquipment != null) {
                lblEquipmentDetails.setText("Item: " + selectedEquipment.getBrand() + " " + selectedEquipment.getModel());
                lblDailyPrice.setText("Price: " + selectedEquipment.getBasePricePerDay());
                
                String status = selectedEquipment.getStatus();
                lblAvailability.setText("Status: " + status);
                
                if ("AVAILABLE".equalsIgnoreCase(status)) {
                    lblAvailability.setForeground(new java.awt.Color(0, 153, 51)); // Green
                } else {
                    lblAvailability.setForeground(java.awt.Color.RED);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Equipment not found!");
                selectedEquipment = null;
                lblEquipmentDetails.setText("Item: -");
                lblAvailability.setText("Status: -");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error searching equipment");
        }
    }//GEN-LAST:event_btnSearchEquipmentActionPerformed

    private void btnPlaceRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceRentalActionPerformed
        placeRental();
    }//GEN-LAST:event_btnPlaceRentalActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPlaceRental;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JButton btnSearchEquipment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblBaseTotal;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblCustomerId1;
    private javax.swing.JLabel lblCustomerId2;
    private javax.swing.JLabel lblCustomerId3;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDailyPrice;
    private javax.swing.JLabel lblDeposite;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblEquipmentDetails;
    private javax.swing.JLabel lblFinalTotal;
    private javax.swing.JLabel lblMembership;
    private javax.swing.JLabel lblTotalDays;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtEquipmentId;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables

    private void calculate() {
        if (selectedCustomer == null || selectedEquipment == null) {
            JOptionPane.showMessageDialog(this, "Please select Customer and Equipment first.");
            return;
        }
        
        // 1. Validation: Is Equipment Available?
        if (!"AVAILABLE".equalsIgnoreCase(selectedEquipment.getStatus())) {
            JOptionPane.showMessageDialog(this, "Equipment is NOT available for rent!");
            return;
        }

        String startDateStr = txtStartDate.getText().trim();
        String endDateStr = txtEndDate.getText().trim();

        try {
            // 2. Parse Dates
            Date startDate = sdf.parse(startDateStr);
            Date endDate = sdf.parse(endDateStr);

            // 3. Calculate Duration
            long diffInMillies = endDate.getTime() - startDate.getTime();
            long diffInDays = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);

            if (diffInDays <= 0) {
                JOptionPane.showMessageDialog(this, "End date must be after Start date!");
                return;
            }
            
            if (diffInDays > 30) {
                JOptionPane.showMessageDialog(this, "Rental duration cannot exceed 30 days!");
                return;
            }

            // 4. Calculate Base Price
            double basePricePerDay = selectedEquipment.getBasePricePerDay();
            double baseTotal = basePricePerDay * diffInDays;

            // 5. Calculate Membership Discount
            String level = selectedCustomer.getMembershipLevelCode();
            double discountPercentage = 0.0;
            
            if ("SILVER".equalsIgnoreCase(level)) {
                discountPercentage = 0.05; // 5%
            } else if ("GOLD".equalsIgnoreCase(level)) {
                discountPercentage = 0.10; // 10%
            }
            
            double membershipDiscount = baseTotal * discountPercentage;

            // 6. Final Calculation
            double totalAfterDiscount = baseTotal - membershipDiscount;
            
            // Set values to labels
            lblTotalDays.setText("Total Days: " + diffInDays);
            lblBaseTotal.setText("Base Rental: " + String.format("%.2f", baseTotal));
            lblDiscount.setText("Discount (" + (discountPercentage*100) + "%): " + String.format("%.2f", membershipDiscount));
            lblDeposite.setText("Security Deposit: " + selectedEquipment.getSecurityDeposit());
            
            this.calculatedFinalTotal = totalAfterDiscount;
            lblFinalTotal.setText("TOTAL: " + String.format("%.2f", totalAfterDiscount));
            
            // Enable Save button
            btnPlaceRental.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid Date Format. Use yyyy-MM-dd");
            e.printStackTrace();
        }
    }

    private void placeRental() {
        try {
            // Create the DTO
            RentalDto dto = new RentalDto();
            dto.setRentalId("R" + (System.currentTimeMillis() / 1000)); // Generate Unique ID
            dto.setEquipmentId(selectedEquipment.getEquipmentId());
            dto.setCustomerId(selectedCustomer.getCustomerId());
            // FIX: If current user is Admin (null branch), use the Equipment's branch instead.
            String finalBranchId;
            if (currentUser != null && currentUser.getBranchId() != null) {
                finalBranchId = currentUser.getBranchId();
            } else {
                // Fallback: If user is Admin, the rental happens at the equipment's branch
                finalBranchId = selectedEquipment.getBranchId();
            }
            dto.setBranchId(finalBranchId);
            
            dto.setIssuedBy(currentUser != null ? currentUser.getUserId() : "ADMIN");
            dto.setStartDate(sdf.parse(txtStartDate.getText().trim()));
            dto.setEndDate(sdf.parse(txtEndDate.getText().trim()));
            
            // Financials
            dto.setCalculatedRentalAmount(Double.parseDouble(lblBaseTotal.getText().split(": ")[1]));
            dto.setMembershipDiscount(Double.parseDouble(lblDiscount.getText().split(": ")[1]));
            dto.setLongRentalDiscount(0.0); // Not implemented in this step, defaulting to 0
            dto.setFinalPayableAmount(calculatedFinalTotal);
            dto.setSecurityDeposit(selectedEquipment.getSecurityDeposit());
            dto.setAmountPaid(0.0); // Assume unpaid initially
            dto.setPaymentStatus("UNPAID");
            dto.setRentalStatus("ACTIVE");

            // Call Controller (Transaction)
            String result = rentalController.placeRental(dto);
            
            JOptionPane.showMessageDialog(this, result);
            
            if (result.contains("successfully")) {
                loadRentalsTable();
                clearForm();
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error placing rental: " + e.getMessage());
        }
    }

    private void clearForm() {
        txtCustomerId.setText("");
        txtEquipmentId.setText("");
        txtStartDate.setText("");
        txtEndDate.setText("");
        lblCustomerName.setText("Name: -");
        lblMembership.setText("Membership: -");
        lblEquipmentDetails.setText("Item: -");
        lblAvailability.setText("Status: -");
        lblDailyPrice.setText("Price: 0.00");
        lblTotalDays.setText("Total Days: 0");
        lblBaseTotal.setText("Base Rental: 0.00");
        lblDiscount.setText("Discount: 0.00");
        lblFinalTotal.setText("TOTAL: 0.00");
        
        selectedCustomer = null;
        selectedEquipment = null;
        btnPlaceRental.setEnabled(false);
    }
    
    private void loadRentalsTable() {
        try {
            // FIX: Explicitly define the column names here
            String[] columns = {"Rental ID", "Customer", "Equipment", "Status"};
            DefaultTableModel dtm = new DefaultTableModel(columns, 0);
            jTable1.setModel(dtm); // Apply this model to the table

            ArrayList<RentalDto> rentals = rentalController.getAllRentals();
            
            for (RentalDto r : rentals) {
                dtm.addRow(new Object[]{
                    r.getRentalId(),
                    r.getCustomerId(),
                    r.getEquipmentId(),
                    r.getRentalStatus()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
